### ISSUE TITLE
fast raxml searches produce an error

### ISSUE THREAD

**Issue by osuchanglab** [kgori/treeCl#14]
After permuting alignments using:
coll = treeCl.Collection(input_dir='./', file_format='fasta', trees_dir='./inputtrees')
c = coll.permuted_copy()

and then calculating  the trees using raxml with the fast tree option:

c.calc_trees(executable='raxmlHPC-PTHREADS-SSE3',  # specify raxml binary to use
    threads=16,  # use multithreaded raxml
    model='GTRGAMMA',  # this model of evolution
    fast_tree=True)

or if I use fast_tree=True in analyze_cache_dir(),
I get the following error:

  File "runscoringRFwardBootInd.py", line 27, in <module>
    results = sc.analyse_cache_dir(executable='raxmlHPC-PTHREADS-SSE3', threads=16, fast_tree=True)
  File "/home/weisberga/lib/python2.7/site-packages/treeCl/collection.py", line 604, in analyse_cache_dir
    result = jobhandler(self.task_interface.get_task(), args, 'Cache dir analysis', batchsize)
  File "/home/weisberga/lib/python2.7/site-packages/treeCl/parutils.py", line 212, in __call__
    return sequential_map(task, args, message)
  File "/home/weisberga/lib/python2.7/site-packages/treeCl/parutils.py", line 115, in sequential_map
    map_result.append(task(*arglist))
  File "/home/weisberga/lib/python2.7/site-packages/treeCl/tasks.py", line 282, in raxml_task
    result = parser.to_dict(info_file, result_file, dash_f_e=dash_f_e)
  File "/home/weisberga/lib/python2.7/site-packages/treeCl/parsers.py", line 211, in to_dict
    return self._dash_f_e_to_dict(info_filename, tree_filename)
  File "/home/weisberga/lib/python2.7/site-packages/treeCl/parsers.py", line 185, in _dash_f_e_to_dict
    models, likelihood, partition_params = self._dash_f_e_parser.parseFile(fl).asList()
  File "/home/weisberga/lib/python2.7/site-packages/pyparsing.py", line 1511, in parseFile
    raise exc
pyparsing.ParseException: Expected ", Type of Data:" (at char 20640), (line:1366, col:57)

The analysis runs to completion if I use fast_tree=False. It looks like something is going wrong when it parses raxml output with the fast tree option. I am using raxml version 8.2.11.

**Comment by kgori** [comment]
Thank you for this report. I will look into whether I need to update the RAxML parser for version 8.2.x.

**Comment by kgori** [comment]
Hi. 

I'm sorry to say that I have not been able to reproduce your error. When I run an analysis using the same version (raxmlHPC-PTHREADS-SSE3; version 8.2.11; GTRGAMMA model) it successfully completes - both the calc_trees and analyse_cache_dir. So I think the problem is not the parser. 

It might help us to find the problem if you switch on debug output. To do this, modify the file treeCl/logging/logging.yaml on line 42, to say:

    level: DEBUG

This will switch on a lot of debug output and tell us a lot more about what RAxML is doing. This change will need to be done in your site-packages, either by modifying the file there directly, or by modifying the file in your local copy of treeCl before installing it with pip.

Sorry I can't be more helpful,
Kevin
